pool:
  vmImage: 'ubuntu-latest'
jobs:
- job: PRBuild
  condition: succeeded()
  strategy:
    matrix:
      'NodeJs 12':
        NodeVersion: 12
  steps:
  - checkout: self
  - template: azure-pipelines/build.yaml
