variables:
  NodeVersion: 12.14.1
pool:
  vmImage: "ubuntu-18.04"
jobs:
- job: PRBuild
  condition: succeeded()
  steps:
    - task: NodeTool@0
      displayName: 'Use Node $(NodeVersion)'
      inputs:
        versionSpec: "$(NodeVersion)"
    - checkout: self
    - template: azure-pipelines/build.yaml